export const electricityProviders = {
    1: "ikeja-electric",
    2: "eko-electric",
    3: "ibadan-electric",
    4: "abuja-electric",
    5: "jos-electric",
    6: "kaduna-electric",
    7: "kano-electric",
    8: "portharcourt-electric",
    9: "enugu-electric",
    10: "aba-electric",
    11: "benin-electric",
    12: "yola-electric",
    "ikeja-electric": "ikeja-electric",
    "eko-electric": "eko-electric",
    "ibadan-electric": "ibadan-electric",
    "abuja-electric": "abuja-electric",
    "jos-electric": "jos-electric",
    "kaduna-electric": "kaduna-electric",
    "kano-electric": "kano-electric",
    "portharcourt-electric": "portharcourt-electric",
    "enugu-electric": "enugu-electric",
    "aba-electric": "aba-electric",
    "benin-electric": "benin-electric",
    "yola-electric": "yola-electric",
};